config/routes.rb
Rails.application.routes.draw do
  root to: "pages#home"
    get "dashboard", to: "pages#dashboard"
    resources :grannies, only:[:index, :show, :new, :create] do
      resources :bookings, only:[:new, :create, :edit]
    end
    resources :bookings, only:[:index, :show]
    patch "bookings/:id/accept", to: "bookings#accept", as: :booking_accept
    patch "bookings/:id/reject", to:"bookings#reject", as: :booking_reject
  devise_for :views
  devise_for :users
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :granny
  belongs_to :user
  # validates :created_at
end

app/models/granny.rb
class Granny < ApplicationRecord
  has_one_attached :photo
  belongs_to :user
  has_many :bookings, dependent: :destroy
  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :age, presence: true
  validates :description, presence: true
  validates :lullaby_skill, presence: true
  validates :storytelling_skill, presence: true
  validates :baking_skill, presence: true
  validates :availability, presence: true
  validates :price_per_day, presence: true

  include PgSearch::Model
  pg_search_scope :search_by_name_and_age,
    against: [:first_name, :last_name, :age, :description],
    using: {
      tsearch: { prefix: true }
    }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :grannies
  has_many :bookings
end

app/models/view.rb
class View < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  before_action :set_booking, only: []
  before_action :set_granny, only: [:new, :create]

  def new
    @booking = Booking.new
  end

  def index
    @bookings = Booking.all
  end

  def show
    @booking = Booking.find(params[:id])
  end

  def create
    @booking = Booking.new(booking_params)
    @booking.granny = @granny
    @booking.user = current_user
    @booking.confirm = "pending"
    if @booking.save
      redirect_to booking_path(@booking)
    else
      render :new
    end
  end

  def accept
    @booking = Booking.find(params[:id])
    @booking.confirm = "accepted"
    @booking.save
    redirect_to dashboard_path
  end

  def reject
    @booking = Booking.find(params[:id])
    @booking.confirm = "rejected"
    @booking.save
    redirect_to dashboard_path
  end

  def edit
    @booking = Booking.find(params[:id])
  end

  private

  def booking_params
    params.require(:booking).permit(:message, :occurs_on, :confirm)
  end

  def set_booking
    @booking = Booking.find(params[:booking_id])
  end

  def set_granny
    @granny = Granny.find(params[:granny_id])
  end
end

app/controllers/grannies_controller.rb
class GranniesController < ApplicationController
  def index
    if params[:query].present?
      @grannies = Granny.search_by_name_and_age(params[:query])
    else
      @grannies = Granny.all
    end
  end

  def show
    @granny = Granny.find(params[:id])
  end

  def new
    @granny = Granny.new
  end

  def create
    @granny = Granny.new(granny_params)
    @granny.user = current_user
    if @granny.save
      redirect_to grannies_path
    else
      render :new_granny, status: :unprocessable_entity
    end
  end

  private

  def granny_params
    params.require(:granny).permit(:first_name, :last_name, :age, :description, :lullaby_skill, :storytelling_skill, :baking_skill, :availability, :price_per_day, :photo)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    @grannies = Granny.all.sample(3)
  end

  def dashboard
    @grannies = current_user.grannies
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bookings/index.html.erb
<div class="container">
  <h2>Welcome to your Bookings</h2>

  <h2><strong>Congratulations you have created your booking!</strong></h2>
  <h2>Please wait for your granny to confirm the booking.<h2>
  <div id="carouselExampleSlidesOnly" class="carousel slide" data-bs-ride="carousel">
    <div class="carousel-inner">
      <div class="carousel-item active d-flex justify-content-center">
        <img src="https://images.unsplash.com/photo-1499306215218-42e51ae058b2?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=870&q=80" class="d-block w-90" alt="...">
      </div>
      <div class="carousel-item">
        <img src="https://images.unsplash.com/photo-1634089916298-9fa27180526c?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=870&q=80" class="d-block w-90" alt="...">
      </div>
      <div class="carousel-item">
        <img src="https://images.unsplash.com/photo-1527529482837-4698179dc6ce?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=870&q=80" class="d-block w-90" alt="...">
      </div>
    </div>
  </div>
</div>

<h4>Your booking summary</h4>
<%# <p class="book-sum">Thank you for booking <b><%= @bookings.granny_id.first_name %></b>. Your booking has been placed successfully, and is pending for host approval.</p> %>
<br/>
<%# <p>From <%= @bookings.occurs_on %> %>
</p>
<p>
Status: pending to be approved by host
</p>

app/views/bookings/new.html.erb
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://images.unsplash.com/photo-1551727028-e050e6ed2f62?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=774&q=80);">
  <div class="container">
  </div>
</div>

<div class="container">
  <div class="new-lists">
    <div class="new-list">
      <h1 class="mt-3">Create a new <strong>booking</strong> !</h1>
      <%= simple_form_for [ @granny, @booking ] do |f| %>
        <%= f.input :occurs_on, html5:true, label: "Booking date", order: [:day, :month, :year] %>
        <%= f.input :message %>
        <%= f.submit "Create", class: "btn btn-success" %>
      <% end %>
    </div>
  </div>
</div>

app/views/bookings/show.html.erb
<div class="d-flex justify-content-center ">
  <div class="formcard">
    <h2 class="mb-5"><strong> Your Booking </strong></h2>
    <% if @booking.confirm == "pending" %>
      <h3>Congratulations you have created your booking!</h3>
      <h3>Please wait for <strong><%= @booking.granny.first_name %></strong> to confirm the booking.<h3>
    <% elsif @booking.confirm == "accepted" %>
      <h3>Congratulations your booking has been <strong>confirmed.</strong></h3>
      <h3 class="mb-5"><strong><%= @booking.granny.first_name %></strong> is happy to see you!</h3>
      <div id="carouselExampleSlidesOnly" class="carousel slide" data-bs-ride="carousel">
        <div class="carousel-inner">
          <div class="carousel-item active d-flex justify-content-center">
            <img src="https://images.unsplash.com/photo-1499306215218-42e51ae058b2?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=870&q=80" class="d-block w-90" alt="...">
          </div>
          <div class="carousel-item">
            <img src="https://images.unsplash.com/photo-1634089916298-9fa27180526c?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=870&q=80" class="d-block w-90" alt="...">
          </div>
          <div class="carousel-item">
            <img src="https://images.unsplash.com/photo-1527529482837-4698179dc6ce?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=870&q=80" class="d-block w-90" alt="...">
          </div>
        </div>
      </div>
    <% elsif @booking.confirm == "rejected" %>
      <h3>We are sorry. Your booking request got <strong>rejected.</strong></h3>
      <h3 class="mb-5"><strong><%= @booking.granny.first_name %></strong> is very busy right now!</h3>
      <div id="carouselExampleSlidesOnly" class="carousel slide" data-bs-ride="carousel">
        <div class="carousel-inner">
          <div class="carousel-item active d-flex justify-content-center">
            <img src="https://cdn.24.co.za/files/Cms/General/d/3068/22bcc95c0a5e41e29839ef52a71592db.jpg" alt="...">
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/grannies/backup_index.html.erb
<h1>ROSS'S NAVBAR</h1>


<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://images.unsplash.com/photo-1634089916298-9fa27180526c?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1170&q=80);">
  <div class="container">
    <h1>Rent a <strong>Granny!</strong></h1>
    <p>Everyone come and get your granny</p>
    <a class="btn btn-primary" href="#">Book</a>
  </div>
</div>


<div class="container" >
      <div class="row d-inline-flex p-2 bd-highlight">
    <% @grannies.each do |granny| %>
        <div class="col-md-4">
          <div class="card" style="width: 21rem;">
            <%# <%= image_tag granny.image_url, class:"card-img-top" %>
            <img class="card-img-top" src="https://images.unsplash.com/photo-1566616213894-2d4e1baee5d8?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=871&q=80" alt="card image cap">
            <div class="card-body">
            <h4 class="card-title"><%= granny.first_name %> <%= granny.last_name %></h4>
            <h5>Age <%= granny.age%> </h5>
            <p>Alive? <%= granny.alive%></p>
          </div>
        </div>
      </div>
    <% end %>

      <%# <div class="col-md-4">
        <div class="card" style="width: 21rem;">
          <img class="card-img-top" src="https://plus.unsplash.com/premium_photo-1664475628445-344f9c816cb0?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=870&q=80" alt="First">
          <div class="card-body">
          <h5 class="card-title">Card title</h5>
          </div>
        </div>
      </div>

      <div class="col-md-4">
        <div class="card" style="width: 21rem;">
          <img class="card-img-top" src="https://images.unsplash.com/photo-1581579438747-1dc8d17bbce4?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=870&q=80" alt="First">
          <div class="card-body">
          <h5 class="card-title">Card title</h5>
        </div>
          </div>
      </div>

      <div class="col-md-4">
        <div class="card" style="width: 21rem;">
          <img class="card-img-top" src="https://images.unsplash.com/photo-1551727028-e050e6ed2f62?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1074&q=80" alt="First">
          <div class="card-body">
          <h5 class="card-title">Card title</h5>
          </div>
        </div>
      </div>

      <div class="col-md-4">
        <div class="card" style="width: 21rem;">
          <img class="card-img-top" src="https://images.unsplash.com/photo-1525289792754-f023db9583fa?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1171&q=80" alt="First">
          <div class="card-body">
          <h5 class="card-title">Card title</h5>
          </div>
        </div>
      </div>

      <div class="col-md-4">
        <div class="card" style="width: 21rem;">
          <img class="card-img-top" src="https://images.unsplash.com/photo-1509050606583-e268652db82a?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1170&q=80" alt="First">
          <div class="card-body">
          <h5 class="card-title">Card title</h5>
          </div>
        </div>
      </div>
    </div>
</div> %>

app/views/grannies/index.html.erb
<div class="container">
  <div class="search my-5 ">
      <%= form_with url: grannies_path, method: :get, class: "d-flex" do %>
        <%= text_field_tag :query,
          params[:query],
          class: "form-control",
          placeholder: "Find a Granny"
        %>
        <%= submit_tag "Find a Granny", class: "btn btn-success" %>
      <% end %>
    </div>
    <div class="cards">
        <% @grannies.each do | granny | %>
          <%= link_to granny_path(granny.id), class: "text-decoration-none text-dark" do %>
            <div class="card-bookmark">
              <%= cl_image_tag granny.photo.key, crop: :fill%>
              <div class="card-bookmark-infos p-2">
                <div>
                  <h3 class="mb-4"><%= granny.first_name %> (<%= granny.age %>)</h3>
                  <p class="mb-3"><strong><%= granny.price_per_day %> EUR</strong> per day</p>
                  <p class="pb-3"><%= granny.description %></p>
                </div>
                <p class="card-rating"><%= rand(6.0..10).round(1) %></p>
              </div>
            </div>
          <% end %>
        <% end %>
      </div>
</div>

app/views/grannies/new.html.erb
<div class="d-flex justify-content-center ">
  <div class="formcard">
    <h2 class="mb-5"> Create your Granny </h2>
    <%= simple_form_for [@granny] do |f| %>
      <%= f.input :first_name, label: "Your first name"%>
      <%= f.input :last_name, label: "Your last name"%>
      <%= f.input :age, label: "Your age" %>
      <%= f.input :description, label: "A little description of yourself"%>
      <%= f.input :photo, as: :file, label: "Add an image of yourself" %>
      <%= f.input :baking_skill, label: "Baking skill", collection: 0..10,  as: :radio_buttons %>
      <%= f.input :lullaby_skill, label: "Lullaby skill", collection: 0..10,  as: :radio_buttons %>
      <%= f.input :storytelling_skill, label: "Storytelling skill", collection: 0..10, as: :radio_buttons %>
      <%= f.input :availability, label: "Your availability"%>
      <%= f.input :price_per_day, label: "Your price per day (in EUR)"%>
      <%= f.submit class:"btn-flat"%>
    <% end %>
  </div>
</div>

app/views/grannies/show.html.erb
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://images.unsplash.com/photo-1575467678930-c7acd65d6470?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=2940&q=80);">
  <div class="show-container">
      <h1 id="show-h1"><%= @granny.first_name %> <%= @granny.last_name %></h1>
      <%= link_to "Book me", new_granny_booking_path(@granny), class:"btn btn-lg btn-success mt-2" %>
  </div>
</div>

<div class="container mt-3">
  <div class="row">
      <div class="col-8">
        <div class="card">
          <div id="card-bio" class="card-body">
            <h2 class="card-title"><%= @granny.first_name %> <%= @granny.last_name %></h2>
            <h3 class="card_text mt-4">Bio:</h3>
            <p class="card-text"><%= @granny.description %></p>
            <h3>Availability:</h3>
            <p class="card-text"><%= @granny.availability %></p>
            <h3 >Price:</h3>
            <p class="card-text"><%= @granny.price_per_day %> €</p>
          </div>
        </div>
      </div>
    <div class="col-4">
      <div class="card">
        <div id="card-skills" class="card-body">
          <h2 class="card-title">Skills:</h2>
          <p class="card-text mt-4">📚 Story telling: <%= @granny.storytelling_skill %>/10</p>
          <p class="card-text">🍰 Baking: <%= @granny.baking_skill %>/10</p>
          <p class="card-text">🛏 Lullaby: <%= @granny.lullaby_skill %>/10</p>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RentAGranny</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>
    <%= render "shared/navbar" %>
    <%= render "shared/flashes" %>
    <%= yield %>
    <%= render "shared/footer" %>
  </body>
</html>

app/views/pages/dashboard.html.erb
<div class="container">

<h1 class="mt-5 mb-5 text-center"> Welcome to your profile: <%= current_user.email %></h1>

  <h3 class="mt-3"><strong> Your Grannies </strong></h3>
        <div class="cards my-5">
            <% @grannies.each do | granny | %>
              <%= link_to granny_path(granny.id), class: "text-decoration-none text-dark" do %>
                <div class="card-bookmark">
                  <%= cl_image_tag granny.photo.key, crop: :fill%>
                  <div class="card-bookmark-infos p-2">
                    <div>
                      <h3 class="mb-4"><%= granny.first_name %> (<%= granny.age %>)</h3>
                      <p class="mb-3"><strong><%= granny.price_per_day %> EUR</strong> per day</p>
                      <p class="pb-3"><%= granny.description %></p>
                    </div>
                    <p class="card-rating"><%= rand(5.0..10.0).round(1) %></p>
                  </div>
                </div>
              <% end %>
            <% end %>
        </div>


  <h3 class="mt-5"><strong> Booking Requests for your Grannies </strong></h3>
      <% @grannies.each do | granny | %>
        <div class="cards my-3">
          <% granny.bookings.each do |booking| %>
            <div class="card-booking">
              <p><strong>Granny:</strong> <%= booking.granny.first_name %> <%= booking.granny.last_name %></p>
              <p><strong>Booking Id:</strong> <%= booking.id %></p>
              <p><strong>Booking Date: </strong><%= booking.occurs_on %></p>
              <p class="mt-2" ><strong>From: </strong><%= booking.user.email %></p>
              <p class="mt-2" ><strong>Message: </strong></p><%= booking.message %>
              <p class="mt-2" ><strong>Booking Status: </strong></p><%= booking.confirm %>
              <p></p>
              <%= link_to "Accept", booking_accept_path(booking), data: {turbo_method: :patch}, class: "btn btn-success" %>
              <%= link_to "Reject", booking_reject_path(booking), data: {turbo_method: :patch}, class: "btn btn-secondary" %>
            </div>
          <% end %>
        </div>
      <% end %>
</div>

app/views/pages/home.html.erb
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://images.unsplash.com/photo-1634089916298-9fa27180526c?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1170&q=80);">
  <div class="container ">
    <h1>Rent a <strong>Granny!</strong></h1>
    <p>Everyone come and get your granny</p>
    <%= link_to "Find a Granny", grannies_path, class: "btn btn-lg btn-success" %>
  </div>
</div>


<div class="container">
<h2 class="d-flex justify-content-center mt-5 mb-5 ">Top 3 Grannies this week 👵🏻</h2>
  <div class="cards">
      <% @grannies.each do | granny | %>
        <%= link_to granny_path(granny.id), class: "text-decoration-none text-dark" do %>
          <div class="card-bookmark">
            <%= cl_image_tag granny.photo.key, crop: :fill%>
            <div class="card-bookmark-infos p-2">
              <div>
                <h3 class="mb-4"><%= granny.first_name %> (<%= granny.age %>)</h3>
                <p class="mb-3"><strong><%= granny.price_per_day %> EUR</strong> per day</p>
                <p class="pb-3"><%= granny.description %></p>
              </div>
              <p class="card-rating"><%= rand(6.0..10).round(1) %></p>
            </div>
          </div>
        <% end %>
      <% end %>
    </div>
</div>

app/views/pages/home_backup.html.erb
  <div class="row y-inline-flex p-2 bd-highlight">
    <% @grannies.each do |granny| %>
      <div class="col-md-4">
        <div class="card-bookmark">
          <img class="card-img-top" src=<%= granny.image_url %>>
            <div class="card-body p-2">
              <h4 class="card-title mb-3"><%= granny.first_name %> <%= granny.last_name %></h4>
              <h5>Age: <%= granny.age%> </h5>
              <p class="mb-1">Price: <%= granny.price_per_day%></p>
              <p>Bio: <%= granny.description %></p>
            </div>
          </div>
        </div>
      <% end %>
  </div>

app/views/pages/index.html.erb
<h1>ROSS'S NAVBAR</h1>


<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://images.unsplash.com/photo-1634089916298-9fa27180526c?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1170&q=80);">
  <div class="container">
    <h1>Rent a <strong>Granny!</strong></h1>
    <p>Everyone come and get your granny</p>
    <a class="btn btn-flat" href="#">Apply now</a>
  </div>
</div>


<div class="container" >
    <div class="row d-inline-flex p-2 bd-highlight">
      <div class="col-md-4">
          <div class="card" style="width: 21rem;">
          <img class="card-img-top" src="https://images.unsplash.com/photo-1566616213894-2d4e1baee5d8?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=871&q=80" alt="card image cap">
          <div class="card-body">
          <h5 class="card-title"></h5>
          </div>
        </div>
      </div>

      <div class="col-md-4">
        <div class="card" style="width: 21rem;">
          <img class="card-img-top" src="https://plus.unsplash.com/premium_photo-1664475628445-344f9c816cb0?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=870&q=80" alt="First">
          <div class="card-body">
          <h5 class="card-title">Card title</h5>
          </div>
        </div>
      </div>

      <div class="col-md-4">
        <div class="card" style="width: 21rem;">
          <img class="card-img-top" src="https://images.unsplash.com/photo-1581579438747-1dc8d17bbce4?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=870&q=80" alt="First">
          <div class="card-body">
          <h5 class="card-title">Card title</h5>
        </div>
          </div>
      </div>

      <div class="col-md-4">
        <div class="card" style="width: 21rem;">
          <img class="card-img-top" src="https://images.unsplash.com/photo-1551727028-e050e6ed2f62?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1074&q=80" alt="First">
          <div class="card-body">
          <h5 class="card-title">Card title</h5>
          </div>
        </div>
      </div>

      <div class="col-md-4">
        <div class="card" style="width: 21rem;">
          <img class="card-img-top" src="https://images.unsplash.com/photo-1525289792754-f023db9583fa?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1171&q=80" alt="First">
          <div class="card-body">
          <h5 class="card-title">Card title</h5>
          </div>
        </div>
      </div>

      <div class="col-md-4">
        <div class="card" style="width: 21rem;">
          <img class="card-img-top" src="https://images.unsplash.com/photo-1509050606583-e268652db82a?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1170&q=80" alt="First">
          <div class="card-body">
          <h5 class="card-title">Card title</h5>
          </div>
        </div>
      </div>

<p>
<h2><% @grannies.each do |granny| %>
 <%= granny.age %>
 <% end %></h2>
</p>
    </div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer">
  <div class="footer-links">
    <a href="#"><i class="fab fa-github"></i></a>
    <a href="#"><i class="fab fa-instagram"></i></a>
    <a href="#"><i class="fab fa-facebook"></i></a>
  </div>
  <div class="footer-copyright">
    This page is made with <i class="fas fa-heart"></i> by Abbas, Christian, Murad and Ross.
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="container-fluid">
    <%= link_to "/", class: "navbar-brand" do %>
      <%= image_tag "https://cdn-icons-png.flaticon.com/512/4855/4855845.png" %>
    <% end %>

    <h3 class="navbar-lewagon container-fluid">Rent-a-Granny</h3>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <% if user_signed_in? %>
          <li class="nav-item active">
            <%= link_to "Home", "/", class: "nav-link" %>
          </li>
          <li class="nav-item active">
            <%= link_to "Dashboard", dashboard_path, class: "nav-link" %>
          </li>
          <li class="nav-item active">
            <%= link_to "Grannies", grannies_path, class: "nav-link" %>
          </li>
          <li class="nav-item dropdown">
            <%= image_tag "https://avatars.githubusercontent.com/u/73883927?v=4", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <%= link_to "Create a Granny", new_granny_path, class: "dropdown-item" %>
              <%= link_to "Bookings", "#", class: "dropdown-item" %>
              <%= link_to "Log out", destroy_user_session_path, data: {turbo_method: :delete}, class: "dropdown-item" %>
            </div>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Login", new_user_session_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>